### ISSUE TITLE
Domination teams are flipped on Frozen City.

### ISSUE THREAD

**Issue by Jman5** [redimp/mwotactics#1]
Hey there, I noticed on Frozen City Domination the teams are flipped. You can tell by looking at the number in the dropship at the start.

Thanks for doing this.

**Comment by redimp** [comment]
Daidachi and Protelis checked the map, Alpha and Beta for team 2 were wrong, the lance drop points and the sides of the teams are correct.

The numbers you see in the dropship are from 1 to 4, since you are in a leopard dropship, which got 4 mechbays.

**Comment by Jman5** [comment]
Yeah sorry, you're right. I kept seeing 1 or 2 over and over and it was lining up with the team sides so I thought they were connected.

**Comment by redimp** [comment]
No worries, thx for the input, due to your report we fixed alpha and beta domination "trailer" spots.
