### ISSUE TITLE
Reorganizing project

### ISSUE THREAD

**Issue by NikoGrano** [redimp/mwotactics#3]
Hey!

I was thinking about taking wottactics back into alive mode. Would you like to merge this stuff into my fork?

I will be handling also the server related shit.

**Comment by redimp** [comment]
Hey Niko9911,

where do I find your fork? 

Please note: My updated are mostly Mechwarrior Online related. Adding the Docker stuff was simple and integrating it in your fork might be a walk in the park.

Cheers, Ralph

**Comment by NikoGrano** [comment]
Well, the thing little escalated and the work decided to put down before it even started...

We have new project to replace current wottactic. If you are interested, check out https://gametactic.eu
