### ISSUE TITLE
Illegal use of Wottactic.com

### ISSUE THREAD

**Issue by NikoGrano** [redimp/mwotactics#5]
Hello!

I've noticed your service using illegally wottactic.com upload service. Please stop. I will be taking actions to block this.

```
2020/06/30 13:12:25 [error] 2263#0: *301400 client intended to send too large body: 1527003 bytes, client: 2001:7c7:2135:6500:c9ec:39d4:8d67:6ace, server: _, request: "POST /upload//upload.php HTTP/1.1", host: "forum.wottactic.com", referrer: "https://maps.mwocomp.com/wot2?room=ksYM2IIKTCWNJg"
```

**Comment by NikoGrano** [comment]
Blocked with CORS & some other non-disclosed actions.

**Comment by redimp** [comment]
@NikoGrano I'm extremely sorry for any inconvenience caused.

I check if I find a nice way for disabling the upload feature. This was never intended for use.
